
/*
	DX11 Depth Of Field
	pretty much just does bokeh texture splatting

	basic algorithm:

	* find bright spots
	* verify high frequency (otherwise dont care)
	* if possitive, replace with black pixel and add to append buffer
	* box blur buffer (thus smearing black pixels)
	* blend bokeh texture sprites via append buffer on top of box blurred buffer
	* composite with frame buffer
*/

Shader "Hidden/Dof/DX11Dof" 
{
	Properties 
	{
		_MainTex ("", 2D) = "white" {}
		_BlurredColor ("", 2D) = "white" {}
		_FgCocMask ("", 2D) = "white" {}
	}

	#LINE 129


SubShader 
{

// pass 0: append buffer "collect"

Pass
{
	ZWrite Off ZTest Always Cull Off Fog { Mode Off }

	Program "vp" {
// Vertex combos: 1
//   d3d11 - ALU: 6 to 6, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 64 // 32 used size, 5 vars
Vector 16 [_MainTex_TexelSize] 4
ConstBuffer "UnityPerDraw" 336 // 64 used size, 6 vars
Matrix 0 [glstate_matrix_mvp] 4
BindCB "$Globals" 0
BindCB "UnityPerDraw" 1
// 11 instructions, 1 temp regs, 0 temp arrays:
// ALU 6 float, 0 int, 0 uint
// TEX 0 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"vs_5_0
eefiecedbhflbhhegibboomhakpjkjdjjgedglglabaaaaaalmacaaaaadaaaaaa
cmaaaaaaiaaaaaaapaaaaaaaejfdeheoemaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfceeaaklkl
epfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
fmaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaaamadaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklfdeieffimeabaaaafaaaabaahbaaaaaa
gkaiaaabfjaaaaaeegiocaaaaaaaaaaaacaaaaaafjaaaaaeegiocaaaabaaaaaa
aeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaa
abaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaa
egiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
aaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaa
aaaaaaaadgaaaaafnccabaaaaaaaaaaaagaobaaaaaaaaaaadbaaaaaibcaabaaa
aaaaaaaabkiacaaaaaaaaaaaabaaaaaaabeaaaaaaaaaaaaadhaaaaakcccabaaa
aaaaaaaaakaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaabkaabaaaaaaaaaaa
aaaaaaaiccaabaaaaaaaaaaabkbabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadp
dhaaaaajcccabaaaabaaaaaaakaabaaaaaaaaaaabkaabaaaaaaaaaaabkbabaaa
abaaaaaadgaaaaafnccabaaaabaaaaaaagbebaaaabaaaaaadoaaaaab"
}

}
Program "fp" {
// Fragment combos: 1
//   d3d11 - ALU: 15 to 15, TEX: 3 to 3, FLOW: 3 to 3
SubProgram "d3d11 " {
Keywords { }
ConstBuffer "$Globals" 64 // 48 used size, 5 vars
Vector 0 [_BokehParams] 4
Float 44 [_SpawnHeuristic]
BindCB "$Globals" 0
SetTexture 0 [_MainTex] 2D 1
SetTexture 1 [_BlurredColor] 2D 0
SetTexture 2 [_FgCocMask] 2D 2
// 31 instructions, 4 temp regs, 0 temp arrays:
// ALU 12 float, 0 int, 3 uint
// TEX 3 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 2 static, 1 dynamic
"ps_5_0
eefieceddmoljkdckpglmeakcnplanpgfdfeebkcabaaaaaanaaeaaaaadaaaaaa
cmaaaaaajmaaaaaanaaaaaaaejfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheo
cmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaa
apaaaaaafdfgfpfegbhcghgfheaaklklfdeieffipiadaaaafaaaaaaapoaaaaaa
gkaiaaabfjaaaaaeegiocaaaaaaaaaaaadaaaaaafkaaaaadaagabaaaaaaaaaaa
fkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaa
aaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaafibiaaaeaahabaaa
acaaaaaaffffaaaajoaaaaaeaaoabbaaabaaaaaabmaaaaaagcbaaaaddcbabaaa
abaaaaaagcbaaaadmcbabaaaabaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaac
aeaaaaaaefaaaailmcaaaaiaedffbfaapcaabaaaaaaaaaaaegbabaaaabaaaaaa
eghobaaaaaaaaaaaaagabaaaabaaaaaabaaaaaakbcaabaaaabaaaaaaegacbaaa
aaaaaaaaaceaaaaakoehgbdopepndedphdgijbdnaaaaaaaaefaaaailmcaaaaia
edffbfaapcaabaaaacaaaaaaogbkbaaaabaaaaaaeghobaaaabaaaaaaaagabaaa
aaaaaaaabaaaaaakccaabaaaabaaaaaaegacbaaaacaaaaaaaceaaaaakoehgbdo
pepndedphdgijbdnaaaaaaaadiaaaaaiecaabaaaabaaaaaadkaabaaaaaaaaaaa
dkiacaaaaaaaaaaaaaaaaaaadbaaaaahecaabaaaabaaaaaaabeaaaaaaaaaiadp
ckaabaaaabaaaaaadbaaaaahicaabaaaabaaaaaaabeaaaaamnmmmmdndkaabaaa
acaaaaaaabaaaaahecaabaaaabaaaaaadkaabaaaabaaaaaackaabaaaabaaaaaa
dbaaaaaiicaabaaaabaaaaaackiacaaaaaaaaaaaaaaaaaaaakaabaaaabaaaaaa
abaaaaahecaabaaaabaaaaaadkaabaaaabaaaaaackaabaaaabaaaaaaaaaaaaai
bcaabaaaabaaaaaabkaabaiaebaaaaaaabaaaaaaakaabaaaabaaaaaadbaaaaaj
bcaabaaaabaaaaaadkiacaaaaaaaaaaaacaaaaaaakaabaiaibaaaaaaabaaaaaa
abaaaaahbcaabaaaabaaaaaaakaabaaaabaaaaaackaabaaaabaaaaaabpaaaead
akaabaaaabaaaaaaefaaaailmcaaaaiaedffbfaaecaabaaaabaaaaaaogbkbaaa
abaaaaaaeghlbaaaacaaaaaaaagabaaaacaaaaaadiaaaaahbcaabaaaacaaaaaa
dkaabaaaaaaaaaaaabeaaaaaaaaaiaeadgcaaaafbcaabaaaacaaaaaaakaabaaa
acaaaaaadiaaaaahhcaabaaaacaaaaaaegacbaaaaaaaaaaaagaabaaaacaaaaaa
lcaaaaafbcaabaaaadaaaaaaaaoabbaaabaaaaaadgaaaaafdcaabaaaabaaaaaa
ogbkbaaaabaaaaaadgaaaaaficaabaaaabaaaaaaakaabaaaacaaaaaakiaaaaaj
pcoabbaaabaaaaaaakaabaaaadaaaaaaabeaaaaaaaaaaaaaegaobaaaabaaaaaa
dgaaaaaficaabaaaacaaaaaadkaabaaaaaaaaaaakiaaaaajhcoabbaaabaaaaaa
akaabaaaadaaaaaaabeaaaaabaaaaaaajgahbaaaacaaaaaadccaaaakbcaabaaa
abaaaaaadkaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiaeaabeaaaaaaaaaiadp
diaaaaahhccabaaaaaaaaaaaegacbaaaaaaaaaaaagaabaaaabaaaaaadgaaaaaf
iccabaaaaaaaaaaadkaabaaaacaaaaaadoaaaaabbfaaaaabdgaaaaafpccabaaa
aaaaaaaaegaobaaaaaaaaaaadoaaaaab"
}

}

#LINE 198

}

// pass 1: bokeh splatting (low resolution)

Pass {

	ZWrite Off ZTest Always Cull Off Fog { Mode Off }
	Blend One One, One One
	ColorMask RGBA

	Program "vp" {
// Vertex combos: 1
//   d3d11 - ALU: 2 to 2, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
SetBuffer 0 [pointBuffer]
// 8 instructions, 1 temp regs, 0 temp arrays:
// ALU 2 float, 0 int, 0 uint
// TEX 0 (2 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"vs_5_0
eefiecedlajfgkponkfgmlieoonfmkjjfbhcfgmkabaaaaaaeeacaaaaadaaaaaa
cmaaaaaagaaaaaaaoiaaaaaaejfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaa
aaaaaaaaagaaaaaaabaaaaaaaaaaaaaaababaaaafdfgfpfggfhchegfhiejeeaa
epfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadapaaaa
heaaaaaaacaaaaaaaaaaaaaaadaaaaaaabaaaaaaaealaaaaheaaaaaaabaaaaaa
aaaaaaaaadaaaaaaacaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffied
epepfceeaaklklklfdeieffifeabaaaafaaaabaaffaaaaaagkaiaaabkcaaaaae
aahabaaaaaaaaaaabmaaaaaagaaaaaaebcbabaaaaaaaaaaaagaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaadeccabaaaabaaaaaagfaaaaadpccabaaa
acaaaaaagiaaaaacabaaaaaadgaaaaaimccabaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaiadpkhaaaailacodaaiaidjjbjaahcaabaaaaaaaaaaa
akbabaaaaaaaaaaaabeaaaaaaaaaaaaaeghcbaaaaaaaaaaadcaaaaapdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaaceaaaaaaaaaaaeaaaaaaaeaaaaaaaaaaaaaaaaa
aceaaaaaaaaaialpaaaaialpaaaaaaaaaaaaaaaadgaaaaafeccabaaaabaaaaaa
ckaabaaaaaaaaaaadgaaaaagcccabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaa
dgaaaaafbccabaaaaaaaaaaaakaabaaaaaaaaaaakhaaaailacodaaiaidjjbjaa
pccabaaaacaaaaaaakbabaaaaaaaaaaaabeaaaaaamaaaaaaeghobaaaaaaaaaaa
doaaaaab"
}

}
Program "fp" {
// Fragment combos: 1
//   d3d11 - ALU: 11 to 11, TEX: 1 to 1, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
SetTexture 0 [_MainTex] 2D 0
// 16 instructions, 3 temp regs, 0 temp arrays:
// ALU 7 float, 0 int, 4 uint
// TEX 1 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"ps_5_0
eefiecedkanajcfgdhmnegkbjdkjbdjkcfeejfjmabaaaaaacmadaaaaadaaaaaa
cmaaaaaaleaaaaaaoiaaaaaaejfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaahahaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apahaaaaheaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaa
aiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfe
gbhcghgfheaaklklfdeieffidmacaaaafaaaaaaaipaaaaaagkaiaaabfkaaaaad
aagabaaaaaaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaagcbaaaadhcbabaaa
abaaaaaagcbaaaadhcbabaaaacaaaaaagcbaaaaddcbabaaaadaaaaaagfaaaaad
pccabaaaaaaaaaaagiaaaaacadaaaaaaaaaaaaaldcaabaaaaaaaaaaaegbabaia
ebaaaaaaadaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaaaaadiaaaaak
dcaabaaaaaaaaaaaegaabaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaaaa
aaaaaaaadcaaaaajdcaabaaaaaaaaaaaegbabaaaabaaaaaaegbabaaaadaaaaaa
egaabaaaaaaaaaaadbaaaaakmcaabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaagaebaaaaaaaaaaadbaaaaakdcaabaaaabaaaaaaegaabaaa
aaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaaaaaefaaaailmcaaaaia
edffbfaahcaabaaaacaaaaaaegaabaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaaabaaaaahbcaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaa
abaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaabaaaaaaabaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaackaabaaaaaaaaaaaabaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaiadpdgaaaaafhcaabaaaabaaaaaa
egbcbaaaacaaaaaadgaaaaaficaabaaaabaaaaaaabeaaaaaaaaaiadpdgaaaaaf
icaabaaaacaaaaaackbabaaaabaaaaaadiaaaaahpcaabaaaabaaaaaaegaobaaa
abaaaaaaegaobaaaacaaaaaadiaaaaahpccabaaaaaaaaaaaagaabaaaaaaaaaaa
egaobaaaabaaaaaadoaaaaab"
}

}
Program "gp" {
// Geometry combos: 1
//   d3d11 - ALU: 16 to 16, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
ConstBuffer "$Globals" 64 // 44 used size, 5 vars
Vector 0 [_BokehParams] 4
Vector 32 [_Screen] 3
BindCB "$Globals" 0
// 48 instructions, 4 temp regs, 0 temp arrays:
// ALU 16 float, 0 int, 0 uint
// TEX 0 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"gs_5_0
eefiecedcclfjgoncflmcmfekbdlmlgepomchnmoabaaaaaaoeagaaaaadaaaaaa
cmaaaaaaleaaaaaaemabaaaaejfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapapaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadaaaaaaheaaaaaaacaaaaaaaaaaaaaaadaaaaaaabaaaaaa
aeaeaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklepfdehdfjaaaaaaaaeaaaaaa
aiaaaaaaaaaaaaaahiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaa
aaaaaaaaieaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaahaiaaaaaaaaaaaa
ieaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaaaaaaaaaaaaaaieaaaaaa
acaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklfdeieffijaafaaaafaaaacaageabaaaagkaiaaab
fjaaaaaeegiocaaaaaaaaaaaadaaaaaagbaaaaafpcbacaaaabaaaaaaaaaaaaaa
abaaaaaafpaaaaaedcbacaaaabaaaaaaabaaaaaafpaaaaaeecbacaaaabaaaaaa
abaaaaaafpaaaaaepcbacaaaabaaaaaaacaaaaaagiaaaaacaeaaaaaafnaiaaab
ipaaaaadaaaabbaaaaaaaaaafmciaaabghaaaaaepccabaaaaaaaaaaaabaaaaaa
gfaaaaadhccabaaaabaaaaaagfaaaaadpccabaaaacaaaaaagfaaaaadpccabaaa
adaaaaaafoaaaaacaeaaaaaadgaaaaaimcaabaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadiaaaaajbcaabaaaabaaaaaadkiacaaaaaaaaaaa
aaaaaaaadkbacaaaaaaaaaaaacaaaaaadcaaaaakbcaabaaaabaaaaaaakaabaaa
abaaaaaaakiacaaaaaaaaaaaaaaaaaaaabeaaaaaaaaaaadpebaaaaafccaabaaa
abaaaaaaakaabaaaabaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaaabaaaaaa
abeaaaaaaaaaaaeaabeaaaaaaaaaiadpdcaaaaajccaabaaaabaaaaaabkaabaaa
abaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaeaeadiaaaaaidcaabaaaacaaaaaa
fgafbaaaabaaaaaaegiacaaaaaaaaaaaacaaaaaaaoaaaaahccaabaaaabaaaaaa
bkaabaaaabaaaaaaakaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaakaabaaaabaaaaaaaoaaaaaibcaabaaaabaaaaaabkiacaaaaaaaaaaa
aaaaaaaaakaabaaaabaaaaaadiaaaaaipcaabaaaadaaaaaaagaabaaaabaaaaaa
egbocaaaaaaaaaaaacaaaaaadiaaaaakdcaabaaaaaaaaaaaegaabaaaacaaaaaa
aceaaaaaaaaaialpaaaaiadpaaaaaaaaaaaaaaaaaaaaaaaipcaabaaaaaaaaaaa
egaobaaaaaaaaaaaegbocaaaaaaaaaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaaidccabaaaabaaaaaaaceaaaaaaaaaaaaaaaaaiadp
aaaaaaaaaaaaaaaadgaaaaageccabaaaabaaaaaackbacaaaaaaaaaaaabaaaaaa
dgaaaaafpccabaaaacaaaaaaegaobaaaadaaaaaadgaaaaafdccabaaaadaaaaaa
fgafbaaaabaaaaaadgaaaaaimccabaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaahfaaaaadaaaabbaaaaaaaaaadgaaaaafecaabaaaacaaaaaa
abeaaaaaaaaaaaaaaaaaaaaipcaabaaaaaaaaaaaegakbaaaacaaaaaaegbocaaa
aaaaaaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaai
dccabaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaaaaadgaaaaag
eccabaaaabaaaaaackbacaaaaaaaaaaaabaaaaaadgaaaaafpccabaaaacaaaaaa
egaobaaaadaaaaaadgaaaaafdccabaaaadaaaaaafgafbaaaabaaaaaadgaaaaai
mccabaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahfaaaaad
aaaabbaaaaaaaaaadcaaaaanpcaabaaaaaaaaaaaegakbaaaacaaaaaaaceaaaaa
aaaaialpaaaaialpaaaaiadpaaaaiadpegbocaaaaaaaaaaaaaaaaaaadgaaaaaf
pccabaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaaidccabaaaabaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadgaaaaageccabaaaabaaaaaackbacaaa
aaaaaaaaabaaaaaadgaaaaafpccabaaaacaaaaaaegaobaaaadaaaaaadgaaaaaf
dccabaaaadaaaaaafgafbaaaabaaaaaadgaaaaaimccabaaaadaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahfaaaaadaaaabbaaaaaaaaaadgaaaaag
icaabaaaacaaaaaabkaabaiaebaaaaaaacaaaaaaaaaaaaaipcaabaaaaaaaaaaa
mgakbaaaacaaaaaaegbocaaaaaaaaaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaaidccabaaaabaaaaaaaceaaaaaaaaaiadpaaaaaaaa
aaaaaaaaaaaaaaaadgaaaaageccabaaaabaaaaaackbacaaaaaaaaaaaabaaaaaa
dgaaaaafpccabaaaacaaaaaaegaobaaaadaaaaaadgaaaaafdccabaaaadaaaaaa
fgafbaaaabaaaaaadgaaaaaimccabaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaahfaaaaadaaaabbaaaaaaaaaahgaaaaadaaaabbaaaaaaaaaa
doaaaaab"
}

}

#LINE 224

}

// pass 2: bokeh splatting (high resolution)

Pass {

	ZWrite Off ZTest Always Cull Off Fog { Mode Off }
	BlendOp Add, Add
	Blend DstAlpha One, Zero One
	ColorMask RGBA

	Program "vp" {
// Vertex combos: 1
//   d3d11 - ALU: 2 to 2, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
SetBuffer 0 [pointBuffer]
// 8 instructions, 1 temp regs, 0 temp arrays:
// ALU 2 float, 0 int, 0 uint
// TEX 0 (2 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"vs_5_0
eefiecedlajfgkponkfgmlieoonfmkjjfbhcfgmkabaaaaaaeeacaaaaadaaaaaa
cmaaaaaagaaaaaaaoiaaaaaaejfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaa
aaaaaaaaagaaaaaaabaaaaaaaaaaaaaaababaaaafdfgfpfggfhchegfhiejeeaa
epfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadapaaaa
heaaaaaaacaaaaaaaaaaaaaaadaaaaaaabaaaaaaaealaaaaheaaaaaaabaaaaaa
aaaaaaaaadaaaaaaacaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffied
epepfceeaaklklklfdeieffifeabaaaafaaaabaaffaaaaaagkaiaaabkcaaaaae
aahabaaaaaaaaaaabmaaaaaagaaaaaaebcbabaaaaaaaaaaaagaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaadeccabaaaabaaaaaagfaaaaadpccabaaa
acaaaaaagiaaaaacabaaaaaadgaaaaaimccabaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaiadpkhaaaailacodaaiaidjjbjaahcaabaaaaaaaaaaa
akbabaaaaaaaaaaaabeaaaaaaaaaaaaaeghcbaaaaaaaaaaadcaaaaapdcaabaaa
aaaaaaaaegaabaaaaaaaaaaaaceaaaaaaaaaaaeaaaaaaaeaaaaaaaaaaaaaaaaa
aceaaaaaaaaaialpaaaaialpaaaaaaaaaaaaaaaadgaaaaafeccabaaaabaaaaaa
ckaabaaaaaaaaaaadgaaaaagcccabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaa
dgaaaaafbccabaaaaaaaaaaaakaabaaaaaaaaaaakhaaaailacodaaiaidjjbjaa
pccabaaaacaaaaaaakbabaaaaaaaaaaaabeaaaaaamaaaaaaeghobaaaaaaaaaaa
doaaaaab"
}

}
Program "fp" {
// Fragment combos: 1
//   d3d11 - ALU: 11 to 11, TEX: 1 to 1, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
SetTexture 0 [_MainTex] 2D 0
// 16 instructions, 3 temp regs, 0 temp arrays:
// ALU 7 float, 0 int, 4 uint
// TEX 1 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"ps_5_0
eefiecedkanajcfgdhmnegkbjdkjbdjkcfeejfjmabaaaaaacmadaaaaadaaaaaa
cmaaaaaaleaaaaaaoiaaaaaaejfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaahahaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apahaaaaheaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaa
aiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfe
gbhcghgfheaaklklfdeieffidmacaaaafaaaaaaaipaaaaaagkaiaaabfkaaaaad
aagabaaaaaaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaagcbaaaadhcbabaaa
abaaaaaagcbaaaadhcbabaaaacaaaaaagcbaaaaddcbabaaaadaaaaaagfaaaaad
pccabaaaaaaaaaaagiaaaaacadaaaaaaaaaaaaaldcaabaaaaaaaaaaaegbabaia
ebaaaaaaadaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaaaaadiaaaaak
dcaabaaaaaaaaaaaegaabaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaaaa
aaaaaaaadcaaaaajdcaabaaaaaaaaaaaegbabaaaabaaaaaaegbabaaaadaaaaaa
egaabaaaaaaaaaaadbaaaaakmcaabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaagaebaaaaaaaaaaadbaaaaakdcaabaaaabaaaaaaegaabaaa
aaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaaaaaefaaaailmcaaaaia
edffbfaahcaabaaaacaaaaaaegaabaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaaabaaaaahbcaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaabaaaaaa
abaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaabaaaaaaabaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaackaabaaaaaaaaaaaabaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaiadpdgaaaaafhcaabaaaabaaaaaa
egbcbaaaacaaaaaadgaaaaaficaabaaaabaaaaaaabeaaaaaaaaaiadpdgaaaaaf
icaabaaaacaaaaaackbabaaaabaaaaaadiaaaaahpcaabaaaabaaaaaaegaobaaa
abaaaaaaegaobaaaacaaaaaadiaaaaahpccabaaaaaaaaaaaagaabaaaaaaaaaaa
egaobaaaabaaaaaadoaaaaab"
}

}
Program "gp" {
// Geometry combos: 1
//   d3d11 - ALU: 16 to 16, TEX: 0 to 0, FLOW: 1 to 1
SubProgram "d3d11 " {
Keywords { }
ConstBuffer "$Globals" 64 // 44 used size, 5 vars
Vector 0 [_BokehParams] 4
Vector 32 [_Screen] 3
BindCB "$Globals" 0
// 48 instructions, 4 temp regs, 0 temp arrays:
// ALU 16 float, 0 int, 0 uint
// TEX 0 (0 load, 0 comp, 0 bias, 0 grad)
// FLOW 1 static, 0 dynamic
"gs_5_0
eefiecedcclfjgoncflmcmfekbdlmlgepomchnmoabaaaaaaoeagaaaaadaaaaaa
cmaaaaaaleaaaaaaemabaaaaejfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapapaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadaaaaaaheaaaaaaacaaaaaaaaaaaaaaadaaaaaaabaaaaaa
aeaeaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapapaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklepfdehdfjaaaaaaaaeaaaaaa
aiaaaaaaaaaaaaaahiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaa
aaaaaaaaieaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaahaiaaaaaaaaaaaa
ieaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaaaaaaaaaaaaaaieaaaaaa
acaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklfdeieffijaafaaaafaaaacaageabaaaagkaiaaab
fjaaaaaeegiocaaaaaaaaaaaadaaaaaagbaaaaafpcbacaaaabaaaaaaaaaaaaaa
abaaaaaafpaaaaaedcbacaaaabaaaaaaabaaaaaafpaaaaaeecbacaaaabaaaaaa
abaaaaaafpaaaaaepcbacaaaabaaaaaaacaaaaaagiaaaaacaeaaaaaafnaiaaab
ipaaaaadaaaabbaaaaaaaaaafmciaaabghaaaaaepccabaaaaaaaaaaaabaaaaaa
gfaaaaadhccabaaaabaaaaaagfaaaaadpccabaaaacaaaaaagfaaaaadpccabaaa
adaaaaaafoaaaaacaeaaaaaadgaaaaaimcaabaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadiaaaaajbcaabaaaabaaaaaadkiacaaaaaaaaaaa
aaaaaaaadkbacaaaaaaaaaaaacaaaaaadcaaaaakbcaabaaaabaaaaaaakaabaaa
abaaaaaaakiacaaaaaaaaaaaaaaaaaaaabeaaaaaaaaaaadpebaaaaafccaabaaa
abaaaaaaakaabaaaabaaaaaadcaaaaajbcaabaaaabaaaaaaakaabaaaabaaaaaa
abeaaaaaaaaaaaeaabeaaaaaaaaaiadpdcaaaaajccaabaaaabaaaaaabkaabaaa
abaaaaaaabeaaaaaaaaaaaeaabeaaaaaaaaaeaeadiaaaaaidcaabaaaacaaaaaa
fgafbaaaabaaaaaaegiacaaaaaaaaaaaacaaaaaaaoaaaaahccaabaaaabaaaaaa
bkaabaaaabaaaaaaakaabaaaabaaaaaadiaaaaahbcaabaaaabaaaaaaakaabaaa
abaaaaaaakaabaaaabaaaaaaaoaaaaaibcaabaaaabaaaaaabkiacaaaaaaaaaaa
aaaaaaaaakaabaaaabaaaaaadiaaaaaipcaabaaaadaaaaaaagaabaaaabaaaaaa
egbocaaaaaaaaaaaacaaaaaadiaaaaakdcaabaaaaaaaaaaaegaabaaaacaaaaaa
aceaaaaaaaaaialpaaaaiadpaaaaaaaaaaaaaaaaaaaaaaaipcaabaaaaaaaaaaa
egaobaaaaaaaaaaaegbocaaaaaaaaaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaaidccabaaaabaaaaaaaceaaaaaaaaaaaaaaaaaiadp
aaaaaaaaaaaaaaaadgaaaaageccabaaaabaaaaaackbacaaaaaaaaaaaabaaaaaa
dgaaaaafpccabaaaacaaaaaaegaobaaaadaaaaaadgaaaaafdccabaaaadaaaaaa
fgafbaaaabaaaaaadgaaaaaimccabaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaahfaaaaadaaaabbaaaaaaaaaadgaaaaafecaabaaaacaaaaaa
abeaaaaaaaaaaaaaaaaaaaaipcaabaaaaaaaaaaaegakbaaaacaaaaaaegbocaaa
aaaaaaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaai
dccabaaaabaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaaaaaaaaaadgaaaaag
eccabaaaabaaaaaackbacaaaaaaaaaaaabaaaaaadgaaaaafpccabaaaacaaaaaa
egaobaaaadaaaaaadgaaaaafdccabaaaadaaaaaafgafbaaaabaaaaaadgaaaaai
mccabaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahfaaaaad
aaaabbaaaaaaaaaadcaaaaanpcaabaaaaaaaaaaaegakbaaaacaaaaaaaceaaaaa
aaaaialpaaaaialpaaaaiadpaaaaiadpegbocaaaaaaaaaaaaaaaaaaadgaaaaaf
pccabaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaaidccabaaaabaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadgaaaaageccabaaaabaaaaaackbacaaa
aaaaaaaaabaaaaaadgaaaaafpccabaaaacaaaaaaegaobaaaadaaaaaadgaaaaaf
dccabaaaadaaaaaafgafbaaaabaaaaaadgaaaaaimccabaaaadaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahfaaaaadaaaabbaaaaaaaaaadgaaaaag
icaabaaaacaaaaaabkaabaiaebaaaaaaacaaaaaaaaaaaaaipcaabaaaaaaaaaaa
mgakbaaaacaaaaaaegbocaaaaaaaaaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaaidccabaaaabaaaaaaaceaaaaaaaaaiadpaaaaaaaa
aaaaaaaaaaaaaaaadgaaaaageccabaaaabaaaaaackbacaaaaaaaaaaaabaaaaaa
dgaaaaafpccabaaaacaaaaaaegaobaaaadaaaaaadgaaaaafdccabaaaadaaaaaa
fgafbaaaabaaaaaadgaaaaaimccabaaaadaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaahfaaaaadaaaabbaaaaaaaaaahgaaaaadaaaabbaaaaaaaaaa
doaaaaab"
}

}

#LINE 251

}

}

Fallback Off
}